

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus



  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require_relative '../lib/cookbook'

Ingredients = ['Aleppo pepper',
                'extra-virgin olive oil',
                'red wine vinegar',
                'tomato paste', 'coarse kosher salt',
                'freshly ground black pepper',
                'loves garlic, peeled, flattened',
                'unpeeled lemons; 1 thinly sliced into rounds, 1 cut into wedges for serving',
                'skinless boneless chicken (thighs and/or breast halves), cut into 1 1/4-inch cubes']

Units = ['tablespoons', 'cup', 'tablespoons', 'tablespoons', 'tablespoons', 'teaspoons', 'teaspoons', nil, 'Pounds']

Directions = "throw it in a pot and stir. Serve lukewarm with flat beer"

Amounts = [1.5, 3, 2, 2, 2, 1, 6, 2, 2.25]

Test_recipe = Cookbook::Recipe.new('aleppo chicken', Ingredients, Units, Amounts, Directions)

Hashed = {"Aleppo pepper" => [1.5, "tablespoons"],
         "extra-virgin olive oil" => [3, "cup"],
         "red wine vinegar" => [2, "tablespoons"],
         "tomato paste" => [2, "tablespoons"],
         "coarse kosher salt" => [2, "tablespoons"],
         "freshly ground black pepper" => [1, "teaspoons"],
         "loves garlic, peeled, flattened" => [6, "teaspoons"],
         "unpeeled lemons; 1 thinly sliced into rounds, 1 cut into wedges for serving" =>
             [2, nil],
         "skinless boneless chicken (thighs and/or breast halves), cut into 1 1/4-inch cubes" =>
             [2.25, "Pounds"],
          'name' => 'aleppo chicken'}

Book = Cookbook::Book.new 'Mediterranean Cooking', 'You too can cook good stuff from the Mediterranean'